### ISSUE TITLE
Set up SolrSearch 

### ISSUE THREAD

**Issue by ksclarke** [AppStateLibrary/omeka#3]
http://omeka.org/codex/Plugins/SolrSearch

**Comment by ksclarke** [comment]
Think I resolved the blocking issue (related to the way the dashboard uses javascript and the fact that I had the dev solr proxied through the main site -- since I can't reach the dev site from off campus).  Turning only one on at a time, though a bit of a pain, allows me to work around this (from off campus).  I also have a question in to Tom now about alternatives.

**Comment by ksclarke** [comment]
And, on to the next problem:

2015-03-29T20:03:36+00:00 ERR (3): exception 'Zend_Db_Statement_Mysqli_Exception' with message 'Mysqli prepare error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ')) ORDER BY `items`.`id` ASC LIMIT 100' at line 1' in /home/omeka/devsite/application/libraries/Zend/Db/Statement/Mysqli.php:77
Stack trace:
#0 /home/omeka/devsite/application/libraries/Zend/Db/Statement.php(115): Zend_Db_Statement_Mysqli->_prepare('SELECT `items`....')
#1 /home/omeka/devsite/application/libraries/Zend/Db/Adapter/Mysqli.php(388): Zend_Db_Statement->__construct(Object(Zend_Db_Adapter_Mysqli), 'SELECT `items`....')
#2 /home/omeka/devsite/application/libraries/Zend/Db/Adapter/Abstract.php(479): Zend_Db_Adapter_Mysqli->prepare('SELECT `items`....')
#3 [internal function]: Zend_Db_Adapter_Abstract->query(Object(Omeka_Db_Select), Array)
#4 /home/omeka/devsite/application/libraries/Omeka/Db.php(79): call_user_func_array(Array, Array)
#5 /home/omeka/devsite/application/libraries/Omeka/Db/Table.php(648): Omeka_Db->__call('query', Array)
#6 /home/omeka/devsite/application/libraries/Omeka/Db/Table.php(648): Omeka_Db->query(Object(Omeka_Db_Select), Array)
#7 /home/omeka/devsite/plugins/SolrSearch/lib/SolrSearch/DbPager.php(90): Omeka_Db_Table->fetchObjects(Object(Omeka_Db_Select), Array)
#8 /home/omeka/devsite/plugins/SolrSearch/helpers/SolrSearch_Helpers_Index.php(237): SolrSearch_DbPager->next()
#9 /home/omeka/devsite/plugins/SolrSearch/jobs/SolrSearch_Job_Reindex.php(21): SolrSearch_Helpers_Index::indexAll()
#10 /home/omeka/devsite/application/libraries/Omeka/Job/Process/Wrapper.php(29): SolrSearch_Job_Reindex->perform()
#11 /home/omeka/devsite/application/scripts/background.php(61): Omeka_Job_Process_Wrapper->run(Array)
#12 {main}

**Comment by ksclarke** [comment]
Seems this has been fixed and we should upgrade our SolrSearch to the latest version

scholarslab/SolrSearch#112

**Comment by ksclarke** [comment]
TODO: I changed the version of Solr so will need to re-add the Omeka schema configs again.

**Comment by ksclarke** [comment]
In place on the dev server: http://omeka.library.appstate.edu/devsite/solr-search?q=banjo

Seeking comments before moving to production.

**Comment by ksclarke** [comment]
Moved omeka_dev over to axis machine because there were too many hurdles accessing digital-dev from off-campus.  It can be accessed now at:

http://omeka.library.appstate.edu:8081/solr-search?q=

**Comment by ksclarke** [comment]
Hmm, the new Solr seems to be stopping at 1820 records rather than the full 14k.  Pointing the new Omeka site back to the old Solr instance until this is resolved.

**Comment by ksclarke** [comment]
Set to synchronously index (to get errors in the errors.log):

[Sun Feb 14 16:37:01 2016] [error] [client 66.169.72.97] PHP Fatal error:  Allowed memory size of 268435456 bytes exhausted (tried to allocate 83 bytes) in /home/omeka_dev/application/libraries/Zend/Db/Statement/Mysqli.php on line 235, referer: http://axis001.library.appstate.edu:8081/admin/solr-search/reindex
[Sun Feb 14 16:37:01 2016] [error] [client 66.169.72.97] PHP Stack trace:, referer: http://axis001.library.appstate.edu:8081/admin/solr-search/reindex
[Sun Feb 14 16:37:01 2016] [error] [client 66.169.72.97] PHP   1. {main}() /home/omeka_dev/admin/index.php:0, referer: http://axis001.library.appstate.edu:8081/admin/solr-search/reindex
[Sun Feb 14 16:37:01 2016] [error] [client 66.169.72.97] PHP   2. Omeka_Application->run() /home/omeka_dev/admin/index.php:28, referer: http://axis001.library.appstate.edu:8081/admin/solr-search/reindex
[Sun Feb 14 16:37:01 2016] [error] [client 66.169.72.97] PHP   3. Zend_Application->run() /home/omeka_dev/application/libraries/Omeka/Application.php:79, referer: http://axis001.library.appstate.edu:8081/admin/solr-search/reindex
[Sun Feb 14 16:37:01 2016] [error] [client 66.169.72.97] PHP   4. Zend_Application_Bootstrap_Bootstrap->run() /home/omeka_dev/application/libraries/Zend/Application.php:384, referer: http://axis001.library.appstate.edu:8081/admin/solr-search/reindex
[Sun Feb 14 16:37:01 2016] [error] [client 66.169.72.97] PHP   5. Zend_Controller_Front->dispatch() /home/omeka_dev/application/libraries/Zend/Application/Bootstrap/Bootstrap.php:105, referer: http://axis001.library.appstate.edu:8081/admin/solr-search/reindex
[Sun Feb 14 16:37:01 2016] [error] [client 66.169.72.97] PHP   6. Zend_Controller_Dispatcher_Standard->dispatch() /home/omeka_dev/application/libraries/Zend/Controller/Front.php:954, referer: http://axis001.library.appstate.edu:8081/admin/solr-search/reindex
[Sun Feb 14 16:37:01 2016] [error] [client 66.169.72.97] PHP   7. Zend_Controller_Action->dispatch() /home/omeka_dev/application/libraries/Zend/Controller/Dispatcher/Standard.php:308, referer: http://axis001.library.appstate.edu:8081/admin/solr-search/reindex
[Sun Feb 14 16:37:01 2016] [error] [client 66.169.72.97] PHP   8. SolrSearch_AdminController->reindexAction() /home/omeka_dev/application/libraries/Zend/Controller/Action.php:516, referer: http://axis001.library.appstate.edu:8081/admin/solr-search/reindex
[Sun Feb 14 16:37:01 2016] [error] [client 66.169.72.97] PHP   9. Omeka_Job_Dispatcher_Default->sendLongRunning() /home/omeka_dev/plugins/SolrSearch/controllers/AdminController.php:232, referer: http://axis001.library.appstate.edu:8081/admin/solr-search/reindex
[Sun Feb 14 16:37:01 2016] [error] [client 66.169.72.97] PHP  10. Omeka_Job_Dispatcher_Adapter_Synchronous->send() /home/omeka_dev/application/libraries/Omeka/Job/Dispatcher/Default.php:150, referer: http://axis001.library.appstate.edu:8081/admin/solr-search/reindex
[Sun Feb 14 16:37:01 2016] [error] [client 66.169.72.97] PHP  11. SolrSearch_Job_Reindex->perform() /home/omeka_dev/application/libraries/Omeka/Job/Dispatcher/Adapter/Synchronous.php:25, referer: http://axis001.library.appstate.edu:8081/admin/solr-search/reindex
[Sun Feb 14 16:37:01 2016] [error] [client 66.169.72.97] PHP  12. SolrSearch_Helpers_Index::indexAll() /home/omeka_dev/plugins/SolrSearch/jobs/SolrSearch_Job_Reindex.php:21, referer: http://axis001.library.appstate.edu:8081/admin/solr-search/reindex
[Sun Feb 14 16:37:01 2016] [error] [client 66.169.72.97] PHP  13. SolrSearch_Helpers_Index::itemToDocument() /home/omeka_dev/plugins/SolrSearch/helpers/SolrSearch_Helpers_Index.php:248, referer: http://axis001.library.appstate.edu:8081/admin/solr-search/reindex
[Sun Feb 14 16:37:01 2016] [error] [client 66.169.72.97] PHP  14. Item->getFiles() /home/omeka_dev/plugins/SolrSearch/helpers/SolrSearch_Helpers_Index.php:119, referer: http://axis001.library.appstate.edu:8081/admin/solr-search/reindex
[Sun Feb 14 16:37:01 2016] [error] [client 66.169.72.97] PHP  15. Table_File->findByItem() /home/omeka_dev/application/models/Item.php:135, referer: http://axis001.library.appstate.edu:8081/admin/solr-search/reindex
[Sun Feb 14 16:37:01 2016] [error] [client 66.169.72.97] PHP  16. Omeka_Db_Table->fetchObjects() /home/omeka_dev/application/models/Table/File.php:155, referer: http://axis001.library.appstate.edu:8081/admin/solr-search/reindex
[Sun Feb 14 16:37:01 2016] [error] [client 66.169.72.97] PHP  17. Omeka_Db->query() /home/omeka_dev/application/libraries/Omeka/Db/Table.php:648, referer: http://axis001.library.appstate.edu:8081/admin/solr-search/reindex
[Sun Feb 14 16:37:01 2016] [error] [client 66.169.72.97] PHP  18. Omeka_Db->__call() /home/omeka_dev/application/libraries/Omeka/Db/Table.php:648, referer: http://axis001.library.appstate.edu:8081/admin/solr-search/reindex
[Sun Feb 14 16:37:01 2016] [error] [client 66.169.72.97] PHP  19. call_user_func_array:{/home/omeka_dev/application/libraries/Omeka/Db.php:79}() /home/omeka_dev/application/libraries/Omeka/Db.php:79, referer: http://axis001.library.appstate.edu:8081/admin/solr-search/reindex
[Sun Feb 14 16:37:01 2016] [error] [client 66.169.72.97] PHP  20. Zend_Db_Adapter_Abstract->query() /home/omeka_dev/application/libraries/Omeka/Db.php:79, referer: http://axis001.library.appstate.edu:8081/admin/solr-search/reindex
[Sun Feb 14 16:37:01 2016] [error] [client 66.169.72.97] PHP  21. Zend_Db_Statement->execute() /home/omeka_dev/application/libraries/Zend/Db/Adapter/Abstract.php:480, referer: http://axis001.library.appstate.edu:8081/admin/solr-search/reindex
[Sun Feb 14 16:37:01 2016] [error] [client 66.169.72.97] PHP  22. Zend_Db_Statement_Mysqli->_execute() /home/omeka_dev/application/libraries/Zend/Db/Statement.php:303, referer: http://axis001.library.appstate.edu:8081/admin/solr-search/reindex
[Sun Feb 14 16:37:01 2016] [error] [client 66.169.72.97] PHP  23. mysqli_result->fetch_fields() /home/omeka_dev/application/libraries/Zend/Db/Statement/Mysqli.php:235, referer: http://axis001.library.appstate.edu:8081/admin/solr-search/reindex

And, bumping up the memory did get more time indexing but eventually it ran out of memory again.

I see this thread: http://omeka.org/forums/topic/solr-reindex-all-items

And it looks like it's been changed: https://github.com/scholarslab/SolrSearch/blob/master/helpers/SolrSearch_Helpers_Index.php#L224

But it's still hitting a memory limit somewhere. Perhaps also relevant since we want to index PDFs too: http://omeka.org/forums/topic/solr-search-and-large-dataset

Memory of what's being held in memory before sending it to Solr for indexing?

**Comment by ksclarke** [comment]
I have documented in the /etc/php.ini file what the settings need to be to do a full Solr index of Omeka. To find these notes, search in the file for "ksc" -- it lists default values and what they need to be changed to to get the full Omeka database indexed.

This seems like a workaround rather than an actual fix. Omeka should be able to index its full database in Omeka without giving PHP crazy amounts of memory and time to complete the task, but this is something that would need to be changed in the SolrSearch plugin.
